<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.5.3</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<groupId>com.impacsys.core.common.utils</groupId>
	<artifactId>common-utils</artifactId>
	<version>1.0.1</version>
	<packaging>jar</packaging>
	<name>common-utils</name>

	<description>The Impacsys Core Common Utility Library</description>

	<properties>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>17</java.version>
		<jjwt.version>0.12.6</jjwt.version>

	</properties>

	<dependencies>
		<!-- Spring Dependency -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- Utils -->
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>${jjwt.version}</version>
		</dependency>

		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>${jjwt.version}</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId>
			<version>${jjwt.version}</version>
			<scope>runtime</scope>
		</dependency>

		<!-- Test -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

    <distributionManagement>
        <repository>
            <!-- release 버전 올라가는 곳 -->
            <id>nexus-releases</id>
            <url>http://49.50.128.113:8081/repository/maven-releases/</url>
        </repository>
        <snapshotRepository>
            <!-- SNAPSHOT 버전 올라가는 곳 -->
            <id>nexus-snapshots</id>
            <url>http://49.50.128.113:8081/repository/maven-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

</project>
